lang:                en
title:               Midhun Harikumar
tagline:             Random Thoughts!
url:                 https://midhunhk.github.io
paginate:            6
paginate_path:       "/blog/page:num/"
permalink:           pretty

# Assets
# We specify the directory for Jekyll so we can use @imports.
# Only use during development
#sass:
#  sass_dir:          _sass
#  style:            :compressed

# Plugins
plugins:
  - jekyll-feed

# Original About/contact
author:
  name:              Midhunhk
  url:               https://midhunhk.github.io/bio/
  email:             midhunhk at gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/midhunhk/midhunhk.github.io

# Google services
google_analytics: UA-54193565-1

header_pages:
  - blog/index.html
  - about.md

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - github-pages